{{- $root := . }}
{{- $values := $root.Values }}
{{- $deploymentsData := $values.deployments }}
{{- range $values.deployments }}
{{ $currentDeployment := . }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $currentDeployment.name }}
  namespace: {{ $values.namespace.name }}
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    honorTimestamps: true
    interval: 30s
    port: 6443
    scheme: https
    scrapeTimeout: 30s
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: app
  namespaceSelector:
    matchNames:
    - {{ $values.namespace.name }}
  selector:
    matchLabels:
      app: {{ $currentDeployment.name }}
---
{{ end }}
