environment: worker
namespace:
  name: "payments"
# deployments is an array. Hence supports multiple deployments.
deployments:
  - name: payments
    podLabels:
      # prometheus.app/port: "8080"
      # prometheus.app/scrape: "true"
    podAnnotations:
      strategy.spinnaker.io/versioned: "false"
    # containers is an array. Hence supports multiple containers.
    containers:
      - name: payments
        ports:
          - name: httpport
            value: 9090
            servicePort: 80
            servicePortName: httpport
            # nodePort: 32758
        # containerPortName: httpport
        # containerPort: 8000
        # internalServicePort: 80
        # externalNodePort: 32758
        # servicePortName: httpport
        imageName: nanda/modular-monolith
        imageTag: payments-0.1.16
        configMapName: config-plain
        configFileName: config-file
        secretName: secrets-plain
        secretsFileName: secrets-file
        livenessProbe:
          tcpSocket:
            port: 9090
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 9090
          timeoutSeconds: 10
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        env:
          - name: "ADD_FUN"
            value: "Yes"
    rollingUpdate:
      maxSurge: "30%"
      maxUnavailable: "20%"
    replicas: 1 # If hpa is defined, defining replicas count here is incorrect. Let hpa totally manage the replicas.
    # terminationGracePeriodSeconds: 60
configMaps:
  - name: config-plain
    data:
      ADD_FUN: "yes"
configFiles:
  - name: config-file
    file: config.json
    mountPath: /service/config.json
# NOTE: secrets are part of values-secrets.yaml
requiredInfraDependencies:
  name: app-infra
  values:
    # NOTE: All the below values are interpreted from values-infra-secrets-<env>.yaml
    # MYSQL_HOST: $MY_MASTER_DATABASE_HOST
    MYSQL_HOST: $MY_DATABASE_HOST
    MYSQL_PORT: $MY_DATABASE_PORT
    SERVICE_A: $SERVICE_A
# NOTE: nodeLabels renders the nodeSelector block.
# nodeAffinityLabels, although can be used as an alternative to `nodeSelector`, is much more powerful than `nodeSelector`.
# nodeLabels:
#   environment: worker
