name: Auto-Merge main to special branches

on:
  push:
    branches:
      - main

env:
  notify_conflicts_on_slack: "false"

jobs:
  merge-main-to-special-branch:
    strategy:
      matrix:
        release_branch:
          - release
          - restricted
            # Add more special branches as needed

      fail-fast: false

    runs-on: ubuntu-latest
    continue-on-error: false

    steps:

      - name: Generate App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.BRANCH_AUTO_MERGER_APP_ID }}
          private-key: ${{ secrets.BRANCH_AUTO_MERGER_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "modular-monolith"

      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Check if '${{ matrix.release_branch }}' target branch exists
        id: check_branch
        run: |
          if git ls-remote --heads origin ${{ matrix.release_branch }} | grep -q 'refs/heads/${{ matrix.release_branch }}'; then
            echo "branch_exists=true" >> $GITHUB_OUTPUT
          else
            echo "branch_exists=false" >> $GITHUB_OUTPUT
            echo "Release branch ${{ matrix.release_branch }} does not exist. Skipping."
            exit 0
          fi

      - name: Checkout '${{ matrix.release_branch }}' target branch
        if: steps.check_branch.outputs.branch_exists == 'true'
        run: |
          git fetch origin ${{ matrix.release_branch }}
          git checkout -b ${{ matrix.release_branch }} origin/${{ matrix.release_branch }}

      - name: Configure git
        if: steps.check_branch.outputs.branch_exists == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Test merging of '${{ github.ref_name }}' branch into '${{ matrix.release_branch }}' branch
        id: merge
        if: steps.check_branch.outputs.branch_exists == 'true'
        run: |
          author=$(git log -1 --format="%an <%ae>" origin/${GITHUB_REF#refs/heads/})
          echo "author=$author" >> $GITHUB_OUTPUT

          # Fetch the latest changes
          git fetch origin ${{ github.ref }}

          # Check if there are any changes to merge
          if git merge-base --is-ancestor origin/${GITHUB_REF#refs/heads/} HEAD; then
            echo "merge_status=up_to_date" >> $GITHUB_OUTPUT
            echo "::notice title=Merge Status::${{ matrix.release_branch }} is already up to date with ${{ github.ref_name }}. No merge needed."
          else
            set +o errexit
            merge_output=$(git merge --no-commit --no-ff --allow-unrelated-histories ${{ github.ref }} 2>&1)
            merge_exit_code=$?
            set -o errexit

            if [ $merge_exit_code -eq 0 ]; then
              echo "merge_status=success" >> $GITHUB_OUTPUT
              echo "::notice title=Merge Status::Merge ${{ github.ref_name }} into ${{ matrix.release_branch }} is possible. No conflicts detected."
              git merge --abort  # Clean up the working directory
            else
              echo "merge_status=conflict" >> $GITHUB_OUTPUT
              echo "::warning title=Merge Conflict::Merge conflict detected in ${{ matrix.release_branch }}. Manual intervention required."

              # Capture and output of conflicts summary
              echo "conflict_summary<<EOF" >> $GITHUB_OUTPUT
              echo "$merge_output" | grep "CONFLICT" >> $GITHUB_OUTPUT
              echo "EOF" >> $GITHUB_OUTPUT

              git merge --abort  # Clean up the working directory
            fi
          fi

      - name: Merge and Push changes
        id: "merge_and_push_changes"
        if: steps.check_branch.outputs.branch_exists == 'true' && steps.merge.outputs.merge_status == 'success'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git merge --no-ff --allow-unrelated-histories ${{ github.ref }} --cleanup=verbatim -m "[Automated] Merge branch '${GITHUB_REF#refs/heads/}' into ${{ matrix.release_branch }}


          skip-checks: true"
          git push -u origin ${{ matrix.release_branch }}
          echo "$(git rev-parse HEAD)" > auto_merge_commit.txt

      - name: Record Merge Commit Hash
        uses: actions/upload-artifact@v4
        with:
          name: auto-merge-commit
          path: auto_merge_commit.txt
          overwrite: true

      - name: Report merge status
        if: always()
        run: |
          if [[ "${{ steps.check_branch.outputs.branch_exists }}" == "false" ]]; then
            echo "::notice title=Branch Status::Branch ${{ matrix.release_branch }} does not exist."
            echo "Branch ${{ matrix.release_branch }} does not exist." >> $GITHUB_STEP_SUMMARY
          elif [[ "${{ steps.merge.outputs.merge_status }}" == "conflict" ]]; then
            echo "::error title=Merge Failed::Merge conflict detected in ${{ matrix.release_branch }}. Manual intervention required."
            echo "Merge conflict detected in ${{ matrix.release_branch }}. Manual intervention required." >> $GITHUB_STEP_SUMMARY
            exit 1
          elif [[ "${{ steps.merge.outputs.merge_status }}" == "success" ]]; then
            echo "::notice title=Merge Successful::Successfully merged ${{ github.ref_name }} into ${{ matrix.release_branch }}."
            echo "Successfully merged '${{ github.ref_name }}' branch into '${{ matrix.release_branch }}' branch." >> $GITHUB_STEP_SUMMARY
          elif [[ "${{ steps.merge.outputs.merge_status }}" == "up_to_date" ]]; then
            echo "::notice title=Branch Up to Date::${{ matrix.release_branch }} is already up to date with ${{ github.ref_name }}."
            echo "${{ matrix.release_branch }} is already up to date with ${{ github.ref_name }}." >> $GITHUB_STEP_SUMMARY
          else
            echo "::error title=Unexpected Status::Unexpected status for ${{ matrix.release_branch }}."
            echo "Unexpected status for ${{ matrix.release_branch }}." >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      - name: Find commit author in Slack
        if: always() && env.notify_conflicts_on_slack == 'true' && steps.merge.outputs.merge_status == 'conflict'
        id: find_commit_author_in_slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.BRANCH_AUTO_MERGER_SLACK_APP_BOT_TOKEN }}
        run: |
          incoming_commit_author=$(echo "${{ steps.merge.outputs.author }}" | sed 's/.*<\(.*\)>/\1/')
          commit_author_slack_handle=$(curl -s -X POST \
            -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "email=$incoming_commit_author" \
            https://slack.com/api/users.lookupByEmail | \
            jq -r 'if .ok == true then .user.id else "Unknown (\(.error))" end')

          if [[ $commit_author_slack_handle == "Unknown"* ]]; then
            echo "Warning: Could not fetch Slack handle for $incoming_commit_author. Using email instead."
            commit_author_slack_handle=$incoming_commit_author
          fi
          echo "commit_author_slack_handle=$commit_author_slack_handle" >> $GITHUB_OUTPUT

      - name: Send Slack notification on conflict
        if: always() && env.notify_conflicts_on_slack == 'true' && steps.merge.outputs.merge_status == 'conflict'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.BRANCH_AUTO_MERGER_SLACK_APP_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_FOOTER: "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Triggered on this workflow run> | <${{ github.server_url }}/${{ github.repository }}|In ${{ github.repository }} repository>"
          SLACK_LINK_NAMES: true
          SLACKIFY_MARKDOWN: true
          SLACK_MESSAGE: |
            Merge conflict detected while merging `${{ github.ref_name }}` into `${{ matrix.release_branch }}` in the `${{ github.repository }}` repository. Manual intervention required. Please visit the Actions URL for more details.
            Author: ${{ contains(steps.find_commit_author_in_slack.outputs.commit_author_slack_handle, '@') && steps.find_commit_author_in_slack.outputs.commit_author_slack_handle || format('<@{0}>', steps.find_commit_author_in_slack.outputs.commit_author_slack_handle) }} (${{ steps.merge.outputs.author }})

            ### Conflict details
            ```
            ${{ steps.merge.outputs.conflict_summary }}
            ```
          SLACK_TITLE: Message
          MSG_MINIMAL: ref,actions url,commit

  check-overall-status:
    needs: merge-main-to-special-branch
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check if any merges failed
        run: |
          if [[ "${{ contains(needs.merge-main-to-special-branch.result, 'failure') }}" == "true" ]]; then
            echo "::error title=Merge Failures::One or more merges failed. Please check the individual job results."
            echo "One or more merges failed. Please check the individual job results." >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo "::notice title=All Merges Successful::All merges completed successfully."
            echo "All merges completed successfully." >> $GITHUB_STEP_SUMMARY
          fi
