name: Check Branch Merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check base branch and source branch
        if: github.base_ref == 'main' && github.head_ref == 'restricted-branch'
        run: |
          echo "Merging from 'restricted-branch' to 'main' is not allowed."
          exit 1
      - name: Success
        if: github.base_ref != 'main' || github.head_ref != 'restricted-branch'
        run: echo "Merge allowed."
