name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ['products', 'payments']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      continue-on-error: false

    - name: Set up Go
      continue-on-error: false
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
        key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-

    - name: Test
      if: contains(github.event.head_commit.modified, '${{ matrix.module }}')
      continue-on-error: false
      run: |
        echo "$(go version)"
        go test -v -cover ./...
      working-directory: ${{ matrix.module }}

    - name: Set up QEMU
      if: contains(github.event.head_commit.modified, '${{ matrix.module }}')
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      if: contains(github.event.head_commit.modified, '${{ matrix.module }}')
      continue-on-error: false
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug

    - name: Login to DockerHub
      if: contains(github.event.head_commit.modified, '${{ matrix.module }}')
      continue-on-error: false
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image for git sha
      if: contains(github.event.head_commit.modified, '${{ matrix.module }}')
      uses: docker/build-push-action@v5
      with:
        context: ./${{ matrix.module }}
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/modular-monolith:${{ matrix.module }}-${{ github.sha }}

    - name: Extract version
      if: contains(github.event.head_commit.modified, '${{ matrix.module }}/version.go')
      id: extract-version
      run: |
        VERSION=`grep -E "MAJOR|MINOR|PATCH" version.go | cut -d '"' -f 2 | xargs echo -n | tr -s " " "."`
        echo "::set-output name=VERSION::$VERSION"
      working-directory: ${{ matrix.module }}

    - name: Check for version change and build & push version-specific Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./${{ matrix.module }}
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/modular-monolith:${{ matrix.module }}-${{ steps.extract-version.outputs.VERSION }}
      if: contains(github.event.head_commit.modified, '${{ matrix.module }}/version.go')
