name: Create Git Tag

on:
  workflow_run:
    workflows:
      - "Auto-Merge main to special branches"
    types:
      - completed
  push:
    branches:
      - release
    paths:
    - '**/version.go'

jobs:
  create-tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - products
          - payments

    steps:
    - name: Retrieve merge commit SHA from auto-merge workflow artifact (if required)
      uses: dawidd6/action-download-artifact@v2
      if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
      with:
        name: auto-merge-commit
        run_id: ${{ github.event.workflow_run.id }}
        workflow: ${{ github.event.workflow_run.workflow_id }}

    - name: Get commit hash
      id: get_commit
      if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
      run: echo "commit_sha=$(cat auto_merge_commit.txt)" >> $GITHUB_OUTPUT

    - name: Checkout code
      uses: actions/checkout@v4
      continue-on-error: false
      with:
        ref: ${{ steps.get_commit.outputs.commit_sha || github.sha }} # Use SHA for upstream workflow run, normal SHA for push
        fetch-depth: 0

    - name: Extract Version
      if: contains(github.event.head_commit.modified, '${{ matrix.module }}/version.go')
      id: extract-version
      run: |
        VERSION=`grep -E "MAJOR|MINOR|PATCH" version.go | cut -d '"' -f 2 | xargs echo -n | tr -s " " "."`
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      working-directory: ${{ matrix.module }}

    - name: Create Tag
      uses: actions/github-script@v7
      with:
        github-token: "${{ github.token }}"
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ matrix.module }}-${{ steps.extract-version.outputs.VERSION }}",
            sha: ${{ steps.get_commit.outputs.commit_sha || context.sha }} # Use SHA for upstream workflow run, normal SHA for push
          })
