name: Go Checks

on: [push, pull_request]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Build
      run: |
        go build -ldflags="-s -w" -a -o server $PWD/products/cmd/server
        go build -ldflags="-s -w" -a -o server $PWD/payments/cmd/server
    # - name: Test
    #   run: go test -v ./...
    # - name: Lint
    #   uses: golangci/golangci-lint-action@v3
    # - name: Format check
    #   run: test -z $(gofmt -l .)
    # - name: Static check
    #   run: |
    #     go install honnef.co/go/tools/cmd/staticcheck@latest
    #     staticcheck ./...
