name: Merge Main/Master to Special Branch

on:
  push:
    branches:
      - main

jobs:
  merge-main-to-special-branch:
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Checkout target branch
        run: |
          git fetch origin restricted
          git checkout origin/restricted

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Merge changes from main/master
        id: merge
        # TODO: Scale the below merge to multiple special branches
        run: |
          git merge --allow-unrelated-histories --no-ff ${{ github.ref }} || echo "Merge conflict detected" > merge_conflict.txt

      - name: Push changes
        if: success()
        run: git push origin restricted

      - name: Check for merge conflict
        if: failure()
        run: cat merge_conflict.txt
