name: Merge Main to Special Branch

on:
  push:
    branches:
      - main

jobs:
  merge-main-to-special-branch:
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Check if target branch exists
        id: check_branch
        run: |
          if git ls-remote --heads origin restricted | grep -q 'refs/heads/restricted'; then
            echo "branch_exists=true" >> $GITHUB_OUTPUT
          else
            echo "branch_exists=false" >> $GITHUB_OUTPUT
            exit 0
          fi

      - name: Checkout target branch
        if: steps.check_branch.outputs.branch_exists == 'true'
        run: |
          git fetch origin restricted
          git checkout origin/restricted

      - name: Configure git
        if: steps.check_branch.outputs.branch_exists == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Merge incoming changes
        id: merge
        if: steps.check_branch.outputs.branch_exists == 'true'
        # TODO: Scale the below merge to multiple special branches
        run: |
          git config --global --list
          git remote -v
          git merge --allow-unrelated-histories --no-ff ${{ github.ref }}

      - name: Push changes
        if: steps.check_branch.outputs.branch_exists == 'true' && steps.merge.outcome == 'success'
        run: git push -u origin restricted

      - name: Check for merge conflict
        if: steps.check_branch.outputs.branch_exists == 'true' && failure() && steps.merge.outcome == 'failure'
        run: |
          git status
          cat .github/workflows/merge-main-to-special-branch.yaml
