name: Block Merge from Specific Branch

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  block_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check base branch and source branch
        if: github.base_ref == 'main' && github.head_ref == 'restricted'
        run: |
          echo "Merging from 'restricted' branch to 'main' is not allowed."
          exit 1
